# Generated by Django 2.1.3 on 2018-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_csv',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
